dist: trusty
matrix:
  include:
    - language: node_js
      node_js:
        - '11'
        - '10'
        - '8'
      before_script:
        - npm i
      script:
        - npm run test-ci
    - language: android
      name: Android
      android:
        components:
          - android-27
          - android-19
          - tools
          - platform-tools
          - build-tools-27.0.3
          - extra-google-m2repository
          - extra-android-m2repository
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - wget
            - pkg-config
      before_install:
        - nvm install 8
        - node --version
        - wget https://github.com/bazelbuild/bazel/releases/download/0.17.2/bazel_0.17.2-linux-x86_64.deb
        - sha256sum -c bazel.sha256
        - sudo dpkg -i bazel_0.17.2-linux-x86_64.deb
        - bazel version
        - sudo apt-get install ant
        - wget https://dl.google.com/android/repository/android-ndk-r17c-linux-x86_64.zip
        - sha1sum -c android-ndk.sha
        - unzip -q android-ndk-r17c-linux-x86_64.zip
        - mv android-ndk-r17c/ ${ANDROID_HOME}/ndk-bundle
      install:
        - echo y | sdkmanager "cmake;3.6.4111459"
        - echo y | sdkmanager "lldb;3.1"
      before_script:
        - export ANDROID_NDK_HOME=$ANDROID_HOME/ndk-bundle
        - npm i
      script:
        - npm run test-android
